/*const comments = [
//  {
//    id: 0,
//    productId: 0,
//    rating: 5,
//    text: "I already need to order more.",
//    author: "Simon Hunt",
//    date: "2018-10-25T16:30Z",
//  },
//  {
    id: 1,
    productId: 1,
    rating: 4,
    text: "UPS smashed my box of goodies. They shipped me another one for free!",
    author: "Zandra Katherine",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 2,
    productId: 3,
    rating: 4,
    text: "I had to hide them from my kids.",
    author: "Amy Keophilavong",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 3,
    productId: 2,
    rating: 4,
    text: "Sweetness overload.",
    author: "Jean Luc",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 4,
    productId: 4,
    rating: 5,
    text: "They arrived very fast and I ate them even faster.",
    author: "R. E. Osariemen",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 5,
    productId: 3,
    rating: 4,
    text: "These rolls need to be available in stores.",
    author: "Juan Cortez",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 6,
    productId: 2,
    rating: 5,
    text: "These rolls were a big hit at my office.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 7,
    productId: 5,
    rating: 5,
    text: "I loved them so much that I could not share.",
    author: "Brennen Ech",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 8,
    productId: 2,
    rating: 4,
    text: "Moist and delicious.",
    author: "Amy Keophilavong",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 9,
    productId: 1,
    rating: 5,
    text: "I will be ordering again very soon.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 10,
    productId: 0,
    rating: 5,
    text: "My sweet tooth was made happy!",
    author: "Olaf the Snowman",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 11,
    productId: 3,
    rating: 5,
    text: "I enjoyed every bite!",
    author: "Vincent and Mona Lisa Gambini",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 12,
    productId: 4,
    rating: 5,
    text: "These are the best rolls I have ever eaten!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 13,
    productId: 5,
    rating: 4,
    text: "Great taste!",
    author: "Amy Keophilavong",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 14,
    productId: 2,
    rating: 5,
    text: "Perfect for breakfast, lunch or dinner.",
    author: "Dave Lister",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 15,
    productId: 3,
    rating: 4,
    text: "You can not eat just one.",
    author: "Markell Richards",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 16,
    productId: 4,
    rating: 5,
    text: "Will be ordering again for special birthday gifts.",
    author: "Amy Keophilavong",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 17,
    productId: 3,
    rating: 5,
    text: "Magnificent!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 18,
    productId: 4,
    rating: 4,
    text: "The rolls are huge and delicious!",
    author: "Chloe Haskins",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 19,
    productId: 2,
    rating: 5,
    text: "The photos do not do justice to this wonderful roll.",
    author: "Minae Lee",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 20,
    productId: 1,
    rating: 5,
    text: "Be sure to grab milk for extra enjoyment.",
    author: "Cindy Thomas",
    date: "2019-02-18T18:12Z",
  },
];

module.exports = comments; */
